nest api funcional e recebendo mensagens da fila

diff --git a/nest-api/Dockerfile b/nest-api/Dockerfile
--- a/nest-api/Dockerfile
+++ b/nest-api/Dockerfile
@@ -3,9 +3,13 @@ FROM node:18-alpine
 WORKDIR /app
 
 COPY package*.json ./
+
 RUN npm install
 
 COPY . .
+
+# ⚠️ Adicionado para mostrar erros de compilação TS
+RUN npm run build || (echo "❌ BUILD FAILED" && cat /app/dist/*.js 2>/dev/null && exit 1)
 
 EXPOSE 3000
 
